tasks:
  - name: mattermost
    command: "nvm install lts/gallium && docker compose up -d && sh init.sh"
ports:
  - name: mattermost
    port: 8065
    onOpen: open-browser
  - name: db
    port: 5432
    onOpen: ignore
