version: "3.9"
networks:
  default:
    name: "mattermost-apps-dev"
services:
  mattermost:
    container_name: mattermost
    image: "mattermost/mattermost-enterprise-edition:7.9.0"
    restart: "unless-stopped"
    network_mode: "host"
    depends_on:
      - "db"
    env_file:
      - "./mattermost/.docker.env"
    environment:
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@localhost:5432/mattermost_test?sslmode=disable\u0026connect_timeout=10"
      MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
      MM_SERVICESETTINGS_SITEURL: "http://localhost:8065"
      MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION: "true"
      MM_SERVICESETTINGS_ENABLEUSERACCESSTOKENS: "true"
      MM_SERVICESETTINGS_ENABLEOAUTHSERVICEPROVIDER: "true"
      MM_SERVICESETTINGsS_ENABLEDEVELOPER: "true"
      MM_SERVICESETTINGS_ENABLETESTING: "true"
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: "true"
      MM_EXPERIMENTALSETTINGS_ENABLEAPPBAR: "true"
      MM_EXPERIMENTALSETTINGS_ENABLETUTORIAL: "false"
      MM_EXPERIMENTALSETTINGS_ENABLEONBOARDING: "false"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_LOGSETTINGS_CONSOLELEVEL: "DEBUG"
      MM_LOGSETTINGS_FILELEVEL: "DEBUG"
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
      MM_FILESETTINGS_MAXFILESIZE: 123524266
      MM_FEATUREFLAGS_AppsEnabled: "true"
      MM_FEATUREFLAGS_PluginApps: "1.2.0"
    volumes:
      - "./mattermost/mm-logs:/mattermost/logs:rw"
  db:
    image: "postgres"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mostest"
      POSTGRES_USER: "mmuser"
      POSTGRES_DB: "mattermost_test"
